[project]
name = "rshiny2python"
version = "0.1.0"
description = "Workshop Repository"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.2.3",
    "plotly>=6.0.1",
    "requests>=2.32.3",
    "shiny>=1.3.0",
    "shinywidgets>=0.5.1",
]
